In [1]:
import pandas as pd

In [2]:
df_US = pd.read_csv("Us_auction_Bounds.csv", sep=";", decimal=".")

In [3]:
df_US.head()

,type_obligation,date_emission,isin,Coupon,date_maturite,ytm,prix,coef_indexation,benchmark,Pays,devise
0,US Treasury,19/02/2026,912810US5,0.0238,15/02/2056,0.025,97.933562,NaN,FED,USA,US
1,US Treasury,22/01/2026,91282CPU9,0.0188,15/01/2036,0.02,99.413260,NaN,FED,USA,US
2,US Treasury,23/10/2025,91282CPH8,0.0113,15/10/2030,0.012,99.726133,NaN,FED,USA,US
3,US Treasury,24/07/2025,91282CNS6,0.0188,15/07/2035,0.017,101.262744,NaN,FED,USA,US
4,US Treasury,17/04/2025,91282CNB3,0.0163,15/04/2030,0.017,99.634784,NaN,FED,USA,US

In [4]:
df_US.tail()

,type_obligation,date_emission,isin,Coupon,date_maturite,ytm,prix,coef_indexation,benchmark,Pays,devise
102,US Treasury,12/12/2004,9128274Y5,0.0388,15/01/2009,,99.580,NaN,FED,USA,US
103,US Treasury,11/12/2013,912810FD5,0.0363,15/04/2028,,98.307,NaN,FED,USA,US
104,US Treasury,08/12/2001,9128273T7,0.0363,15/01/2008,,99.580,NaN,FED,USA,US
105,US Treasury,19/01/1993,9128273A8,0.0363,15/07/2002,,98.307,NaN,FED,USA,US
106,US Treasury,29/01/1997,9128272M3,0.0338,15/01/2007,0.034,99.580,NaN,FED,USA,US

In [5]:
df_Maroc = pd.read_csv("Maroc_Bounds.csv", sep=";", decimal=".")

In [6]:
df_Maroc.head()

,type_obligation,date_emission,isin,Coupon,date_maturite,ytm,prix,coef_indexation,benchmark,Pays,devise
0,T-bond,31/03/2026,NaN,NaN,20/10/2031,0.025719599,100.13,NaN,BAM,Maroc,MAD
1,T-bond,31/03/2026,MA0002018960,0.0290,14/05/2035,0.028833943,100.13,NaN,BAM,Maroc,MAD
2,T-bond,31/03/2026,NaN,0.0305,16/07/2040,,,NaN,BAM,Maroc,MAD
3,T-bond,31/03/2026,MA0002019059,0.0340,21/08/2045,,,NaN,BAM,Maroc,MAD
4,T-bond,31/03/2026,MA0002018986,0.0380,14/02/2056,,,NaN,BAM,Maroc,MAD

In [7]:
df_Maroc.tail()

,type_obligation,date_emission,isin,Coupon,date_maturite,ytm,prix,coef_indexation,benchmark,Pays,devise
15,T-bond,31/03/2026,NaN,0.0260,20/10/2031,0.025504213,100.23,NaN,BAM,Maroc,MAD
16,T-bond,31/03/2026,NaN,0.0290,14/05/2035,,,NaN,BAM,Maroc,MAD
17,T-bond,31/03/2026,NaN,0.0305,16/07/2040,,,NaN,BAM,Maroc,MAD
18,T-bond,31/03/2026,NaN,0.0340,21/08/2045,,,NaN,BAM,Maroc,MAD
19,T-bond,31/03/2026,NaN,0.0380,14/02/2056,,,NaN,BAM,Maroc,MAD

In [8]:
df_Ja = pd.read_csv("Japan_Bounds.csv", sep=";")

In [9]:
df_Ja.head()

,type_obligation,date_emission,isin,Coupon,date_maturite,ytm,prix,coef_indexation,benchmark,Pays,devise
0,JGB,20/11/2007,NaN,0.024,20/03/2048,0.02435,99.10,NaN,BOJ,Japon,JPY
1,JGB,16/05/2008,NaN,0.024,20/03/2048,0.02570,95.77,NaN,BOJ,Japon,JPY
2,JGB,12/11/2008,NaN,0.024,20/03/2048,0.02445,98.87,NaN,BOJ,Japon,JPY
3,JGB,20/02/2009,NaN,0.024,20/03/2048,0.02040,109.66,NaN,BOJ,Japon,JPY
4,JGB,19/05/2009,NaN,0.022,20/03/2049,0.02220,99.47,NaN,BOJ,Japon,JPY

In [10]:
df_Ja.tail()

,type_obligation,date_emission,isin,Coupon,date_maturite,ytm,prix,coef_indexation,benchmark,Pays,devise
87,JGB,29/05/2025,NaN,0.031,20/03/2065,0.03135,99.20,NaN,BOJ,Japon,JPY
88,JGB,24/07/2025,NaN,0.031,20/03/2065,0.03375,94.01,NaN,BOJ,Japon,JPY
89,JGB,26/09/2025,NaN,0.031,20/03/2065,0.03300,95.60,NaN,BOJ,Japon,JPY
90,JGB,27/11/2025,NaN,0.031,20/03/2065,0.03555,90.40,NaN,BOJ,Japon,JPY
91,JGB,29/01/2026,NaN,0.031,20/03/2065,0.03720,87.27,NaN,BOJ,Japon,JPY

In [11]:
df_Fr = pd.read_csv("France_Bonds_data.csv", sep =";")

In [12]:
df_Fr.head()

,type_obligation,date_emission,isin,Coupon,date_maturite,ytm,prix,coef_indexation,benchmark,Pays,devise
0,adju_LT,14/01/1999,FR0000571432,0.04,25/04/2009,0.0381,101.55,NaN,BCE,France,EUR
1,adju_LT,14/01/1999,FR0000571218,0.055,26/04/2009,0.0463,113.98,NaN,BCE,France,EUR
2,adju_MT,28/01/1999,FR0100802273,0.035,27/04/2009,0.0329,101.02,NaN,BCE,France,EUR
3,adju_I,11/02/1999,FR0000571424,0.03,28/04/2009,0.0301,99.91,0.9977,BCE,France,EUR
4,adju_MT,25/02/1999,FR0100059536,0.04,29/04/2009,0.0299,101.33,NaN,BCE,France,EUR

In [13]:
df_Fr.tail()

,type_obligation,date_emission,isin,Coupon,date_maturite,ytm,prix,coef_indexation,benchmark,Pays,devise
191,adju_MT,23/04/2025,FR001400Z2L7,0.027,02/11/2009,0.0273,99.83,0.0,BCE,France,EUR
192,adju_LT,07/07/2025,FR001400WYO4,0.036,03/11/2009,0.0372,98.46,0.0,BCE,France,EUR
193,adju_LT,08/09/2025,FR0014012II5,0.035,04/11/2009,0.0357,99.38,0.0,BCE,France,EUR
194,adju_MT,23/02/2026,FR0014016G71,0.024,05/11/2009,0.0240,100.00,0.0,BCE,France,EUR
195,adju_LT,09/03/2026,FR0014015MU5,0.041,06/11/2009,0.0404,100.87,0.0,BCE,France,EUR

In [14]:
df_GB = pd.read_csv("Grande_Bretagne_Bounds_data.csv", sep=";")

In [15]:
df_GB.head()

,type_obligation,date_emission,isin,Coupon,date_maturite,ytm,prix,coef_indexation,benchmark,Pays,devise
0,Treasury Gilt,19/04/2022,GB00BF0HZ991,0.00750,31/12/2023,NaN,NaN,NaN,BOE,UK,GBP
1,Treasury Gilt,19/04/2022,GB00B7Z53659,0.02250,01/01/2023,NaN,NaN,NaN,BOE,UK,GBP
2,Treasury Gilt,22/01/2021,GB00BMGR2791,0.00125,01/01/2024,-0.025,100.45,NaN,BOE,UK,GBP
3,Treasury Gilt,19/04/2022,GB00BFWFPL34,0.01000,01/01/2024,NaN,NaN,NaN,BOE,UK,GBP
4,Treasury Gilt,19/04/2022,GB00BHBFH458,0.02750,31/12/2024,NaN,NaN,NaN,BOE,UK,GBP

In [16]:
df_GB.tail()

,type_obligation,date_emission,isin,Coupon,date_maturite,ytm,prix,coef_indexation,benchmark,Pays,devise
88,Index-linked Treasury Gilt,21/11/2025,GB00B73ZYW09,0.00250,01/01/2052,2.349,NaN,NaN,BOE,UK,GBP
89,Index-linked Treasury Gilt,14/03/2024,GB00BPSNBG80,0.01250,01/01/2054,1.234,100.39,NaN,BOE,UK,GBP
90,Index-Linked Treasury Gilt,25/03/2021,GB00BYVP4K94,0.00125,01/01/2056,-1.971,209.21,NaN,BOE,UK,GBP
91,Index-linked Treasury Gilt,14/01/2021,GB00BD9MZZ71,0.00125,31/12/2065,-1.980,253.30,NaN,BOE,UK,GBP
92,Index-linked Treasury Gilt,24/11/2021,GB00BM8Z2W66,0.00125,31/12/2073,-2.388,355.94,NaN,BOE,UK,GBP

In [17]:
df_Co = pd.read_csv("Corporate_Bound.csv", sep=";")

In [18]:
df_Co.head()

,type_obligation,date_emission,isin,Coupon,date_maturite,ytm,prix,coef_indexation,benchmark,Pays,devise
0,CORP,NaN,M9887VAA4,0.00500,27/09/2028,NaN,12.000007,NaN,FED,USA,US
1,CORP,15/01/2019,68245XAB5,0.04625,15/01/2022,0.046,100.000000,NaN,FED,USA,US
2,CORP,NaN,68245XAC3,0.04250,15/05/2024,0.029,101.070000,NaN,FED,USA,US
3,CORP,NaN,68245XAE9,0.05000,15/10/2025,0.035,102.518000,NaN,FED,USA,US
4,CORP,NaN,68245XAH2,0.04375,15/01/2028,NaN,97.906000,NaN,FED,USA,US

In [19]:
df_Co.tail()

,type_obligation,date_emission,isin,Coupon,date_maturite,ytm,prix,coef_indexation,benchmark,Pays,devise
39,CORP,NaN,901928AA9,0.0574,15/02/2055,0.059,97.908,NaN,FED,USA,US
40,CORP,NaN,90215BAA5,0.1612,10/01/2028,NaN,100.000,NaN,FED,USA,US
41,CORP,NaN,90215BAB3,0.1576,08/01/2027,NaN,101.800,NaN,FED,USA,US
42,CORP,NaN,90214NAA0,0.0000,01/11/2036,NaN,100.000,NaN,FED,USA,US
43,CORP,NaN,90138RAA4,0.0393,01/07/2041,NaN,0.000,NaN,FED,USA,US

In [20]:
df_Al = pd.read_csv("Allemagne_Bounds.csv", sep=";")

In [21]:
df_Al.head()

,type_obligation,date_emission,isin,Coupon,date_maturite,ytm,prix,coef_indexation,benchmark,Pays,devise
0,Bund,01/04/2026,DE000BU27014,0.025,15/11/2032,0.025,100.24000,NaN,BCA,DE,EUR
1,Green issue,07/04/2026,NaN,NaN,16/11/2032,NaN,NaN,NaN,BCA,DE,EUR
2,Bund,08/04/2026,DE000BU2Z064,0.029,17/11/2032,0.030,99.41000,NaN,BCA,DE,EUR
3,Bubill,13/04/2026,DE000BU0E345,NaN,18/11/2032,NaN,98.43908,NaN,BCA,DE,EUR
4,Bubill,13/04/2026,DE000BU0E402,NaN,19/11/2032,NaN,NaN,NaN,BCA,DE,EUR

In [22]:
df_Al.tail()

,type_obligation,date_emission,isin,Coupon,date_maturite,ytm,prix,coef_indexation,benchmark,Pays,devise
27,Bubill,14/09/2026,DE000BU0E451,NaN,12/12/2032,NaN,NaN,NaN,BCA,DE,EUR
28,Schatz,06/10/2026,DE000BU22155,NaN,13/12/2032,NaN,NaN,NaN,BCA,DE,EUR
29,Bund,07/10/2026,DE000BU27022,NaN,14/12/2032,NaN,NaN,NaN,BCA,DE,EUR
30,Bubill,12/10/2026,DE000BU0E469,NaN,15/12/2032,NaN,NaN,NaN,BCA,DE,EUR
31,Bubill,16/11/2026,DE000BU0E477,NaN,16/12/2032,NaN,NaN,NaN,BCA,DE,EUR

In [23]:
dataset = pd.concat([df_US, df_Al, df_Co, df_Maroc, df_Fr, df_GB, df_Ja], ignore_index=True)
dataset.head()

,type_obligation,date_emission,isin,Coupon,date_maturite,ytm,prix,coef_indexation,benchmark,Pays,devise
0,US Treasury,19/02/2026,912810US5,0.0238,15/02/2056,0.025,97.933562,NaN,FED,USA,US
1,US Treasury,22/01/2026,91282CPU9,0.0188,15/01/2036,0.02,99.41326,NaN,FED,USA,US
2,US Treasury,23/10/2025,91282CPH8,0.0113,15/10/2030,0.012,99.726133,NaN,FED,USA,US
3,US Treasury,24/07/2025,91282CNS6,0.0188,15/07/2035,0.017,101.262744,NaN,FED,USA,US
4,US Treasury,17/04/2025,91282CNB3,0.0163,15/04/2030,0.017,99.634784,NaN,FED,USA,US

In [24]:
dataset.tail()

,type_obligation,date_emission,isin,Coupon,date_maturite,ytm,prix,coef_indexation,benchmark,Pays,devise
579,JGB,29/05/2025,NaN,0.031,20/03/2065,0.03135,99.2,NaN,BOJ,Japon,JPY
580,JGB,24/07/2025,NaN,0.031,20/03/2065,0.03375,94.01,NaN,BOJ,Japon,JPY
581,JGB,26/09/2025,NaN,0.031,20/03/2065,0.033,95.6,NaN,BOJ,Japon,JPY
582,JGB,27/11/2025,NaN,0.031,20/03/2065,0.03555,90.4,NaN,BOJ,Japon,JPY
583,JGB,29/01/2026,NaN,0.031,20/03/2065,0.0372,87.27,NaN,BOJ,Japon,JPY

In [25]:
print(dataset.shape)

(584, 11)

In [26]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 584 entries, 0 to 583
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   type_obligation  584 non-null    object
 1   date_emission    543 non-null    object
 2   isin             474 non-null    object
 3   Coupon           560 non-null    object
 4   date_maturite    584 non-null    object
 5   ytm              492 non-null    object
 6   prix             522 non-null    object
 7   coef_indexation  49 non-null     float64
 8   benchmark        584 non-null    object
 9   Pays             584 non-null    object
 10  devise           584 non-null    object
dtypes: float64(1), object(10)
memory usage: 50.3+ KB

In [27]:
dataset = dataset.drop("coef_indexation", axis=1)

In [28]:
dataset["date_emission"] = dataset["date_emission"].fillna(dataset["date_emission"].mode()[0])

In [29]:
dataset["isin"] = dataset["isin"].fillna("Inconu")

In [30]:
dataset["Coupon"] = pd.to_numeric(dataset["Coupon"], errors="coerce")
dataset["ytm"] = pd.to_numeric(dataset["ytm"], errors="coerce")
dataset["prix"] = pd.to_numeric(dataset["prix"], errors="coerce")

In [31]:
dataset["Coupon"] = dataset["Coupon"].fillna(dataset["Coupon"].mode()[0])
dataset["ytm"] = dataset["ytm"].fillna(dataset["ytm"].mode()[0])
dataset["prix"] = dataset["prix"].fillna(dataset["prix"].mode()[0])

In [32]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 584 entries, 0 to 583
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   type_obligation  584 non-null    object
 1   date_emission    584 non-null    object
 2   isin             584 non-null    object
 3   Coupon           584 non-null    float64
 4   date_maturite    584 non-null    object
 5   ytm              584 non-null    float64
 6   prix             584 non-null    float64
 7   benchmark        584 non-null    object
 8   Pays             584 non-null    object
 9   devise           584 non-null    object
dtypes: float64(3), object(7)
memory usage: 45.8+ KB

In [33]:
dataset.isnull().sum()

type_obligation    0
date_emission      0
isin               0
Coupon             0
date_maturite      0
ytm                0
prix               0
benchmark          0
Pays               0
devise             0
dtype: int64

In [34]:
print(dataset.duplicated().sum())

8

In [35]:
dataset.drop_duplicates(inplace=True)

In [36]:
print(dataset.duplicated().sum())

0

In [37]:
dataset.describe()

           Coupon         ytm        prix
count  576.000000  576.000000  576.000000
mean     0.021775    0.228221   99.896008
std      0.020602    0.949637   17.672369
min      0.000000   -2.819000    0.000000
25%      0.005000    0.004000   98.307000
50%      0.018625    0.013725   99.580000
75%      0.035000    0.031125  100.185000
max      0.161200    5.404000  355.940000

In [38]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 576 entries, 0 to 583
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   type_obligation  576 non-null    object
 1   date_emission    576 non-null    object
 2   isin             576 non-null    object
 3   Coupon           576 non-null    float64
 4   date_maturite    576 non-null    object
 5   ytm              576 non-null    float64
 6   prix             576 non-null    float64
 7   benchmark        576 non-null    object
 8   Pays             576 non-null    object
 9   devise           576 non-null    object
dtypes: float64(3), object(7)
memory usage: 49.5+ KB

In [39]:
dataset.to_csv('dataset_nettoye.csv', index=False, sep=',', encoding='utf-8-sig')